version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
