/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string CEN_Project::Greeter::greeting() {
    oopsies!
    return std::string("This is a test program for our CEN3031 Project. Hello, World! ");
}

int main () {
    CEN_Project::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    return 0;
}
